-- MySQL Script generated by MySQL Workbench
-- qui 22 nov 2018 11:20:59 WET
-- Model: Parque Aquático   Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ParqueAquatico
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ParqueAquatico` ;

-- -----------------------------------------------------
-- Schema ParqueAquatico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ParqueAquatico` ;
USE `ParqueAquatico` ;

-- -----------------------------------------------------
-- Table `ParqueAquatico`.`Atracao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ParqueAquatico`.`Atracao` ;

CREATE TABLE IF NOT EXISTS `ParqueAquatico`.`Atracao` (
  `Id` INT NOT NULL DEFAULT 0,
  `Designacao` VARCHAR(32) NOT NULL DEFAULT 'ASN (atração sem nome)',
  `Zona` VARCHAR(32) NOT NULL DEFAULT 'ZSN (zona sem nome)',
  `Capacidade` INT NOT NULL DEFAULT 0,
  `Duracao` TIME NOT NULL DEFAULT 0,
  `Altura_Minima` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParqueAquatico`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ParqueAquatico`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `ParqueAquatico`.`Categoria` (
  `Id` INT NOT NULL DEFAULT 0,
  `Designacao` VARCHAR(32) NOT NULL DEFAULT 'CSN (categoria sem nome)',
  `Preco` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `Idade_inferior` INT NOT NULL DEFAULT 0,
  `Idade_superior` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParqueAquatico`.`e_visitada_por`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ParqueAquatico`.`e_visitada_por` ;

CREATE TABLE IF NOT EXISTS `ParqueAquatico`.`e_visitada_por` (
  `Data_entrada_fila` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Data_entrada_atracao` DATETIME NULL DEFAULT NULL,
  `Atracao_Id` INT NOT NULL,
  `Utilizador_Id` INT NOT NULL,
  PRIMARY KEY (`Data_entrada_fila`, `Atracao_Id`, `Utilizador_Id`),
  INDEX `fk_e_visitada_por_Atracao1_idx` (`Atracao_Id` ASC) VISIBLE,
  INDEX `fk_e_visitada_por_Utilizador1_idx` (`Utilizador_Id` ASC) VISIBLE,
  CONSTRAINT `fk_e_visitada_por_Atracao1`
    FOREIGN KEY (`Atracao_Id`)
    REFERENCES `ParqueAquatico`.`Atracao` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_e_visitada_por_Utilizador1`
    FOREIGN KEY (`Utilizador_Id`)
    REFERENCES `ParqueAquatico`.`Utilizador` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParqueAquatico`.`Funcionário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ParqueAquatico`.`Funcionário` ;

CREATE TABLE IF NOT EXISTS `ParqueAquatico`.`Funcionário` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(64) NOT NULL DEFAULT 'FSN (funcionário sem nome)',
  `Salario` DECIMAL(6,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParqueAquatico`.`trabalha_em`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ParqueAquatico`.`trabalha_em` ;

CREATE TABLE IF NOT EXISTS `ParqueAquatico`.`trabalha_em` (
  `Data_de_Inicio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Data_de_Fim` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Funcionário_Id` INT NOT NULL,
  `Atracao_Id` INT NOT NULL,
  PRIMARY KEY (`Data_de_Inicio`, `Funcionário_Id`, `Atracao_Id`),
  INDEX `fk_trabalha_em_Funcionário_idx` (`Funcionário_Id` ASC) VISIBLE,
  INDEX `fk_trabalha_em_Atracao1_idx` (`Atracao_Id` ASC) VISIBLE,
  CONSTRAINT `fk_trabalha_em_Funcionário`
    FOREIGN KEY (`Funcionário_Id`)
    REFERENCES `ParqueAquatico`.`Funcionário` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_trabalha_em_Atracao1`
    FOREIGN KEY (`Atracao_Id`)
    REFERENCES `ParqueAquatico`.`Atracao` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParqueAquatico`.`Utilizador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ParqueAquatico`.`Utilizador` ;

CREATE TABLE IF NOT EXISTS `ParqueAquatico`.`Utilizador` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(64) NOT NULL DEFAULT 'USN (utilizador sem nome)',
  `Nacionalidade` VARCHAR(32) NOT NULL DEFAULT 'USNA (sem nacionalidade)',
  `Hora_entrada_parque` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Hora_saida_parque` DATETIME NULL DEFAULT NULL,
  `Categoria_Id` INT NOT NULL,
  `N_Atracoes_Visitadas` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `fk_Utilizador_Categoria1_idx` (`Categoria_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Utilizador_Categoria1`
    FOREIGN KEY (`Categoria_Id`)
    REFERENCES `ParqueAquatico`.`Categoria` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
